### ISSUE TITLE
Save-HTMLReport error

### ISSUE THREAD

**Issue by entwinedgerm** [bwya77/PSHTML-AD-Report#21] opened 2018-12-06 14:04 UTC
Save-HTMLReport : Cannot bind argument to parameter 'ReportContent' because it is null.
At line:1 char:32
+ Save-HTMLReport -ReportContent $FinalReport -ShowReport -ReportName $ ...
+                                ~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Save-HTMLReport], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Save-HTMLReport

Get-HTMLContentDataTable : Cannot bind argument to parameter 'ArrayOfObjects' because it is an empty collection.
At line:1 char:45
+ ... eport.Add($(Get-HTMLContentDataTable $PasswordExpireSoonTable -HideFo ...
+                                          ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-HTMLContentDataTable], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyCollectionNotAllowed,Get-HTMLContentDataTable

**Comment by viorelfoamete** [comment] 2018-12-06 16:48
I have exactly the same problem here, with $PasswordExpireSoonTable and $FinalReport whom I guess is caused by the first

**Comment by entwinedgerm** [comment] 2018-12-06 21:14
I should mention it's running PS5 and Server 2016

**Comment by entwinedgerm** [comment] 2018-12-07 20:49
It corrected the issue on my end. Thanks

**Comment by bwya77** [comment] 2018-12-08 20:46
Merged to master branch

**Closed by bwya77** 2018-12-08 20:46 UTC
Labels: bug
